export const GET_TUTORES = 'GET_TUTORES'
export const GET_TUTOR  = 'GET_TUTOR'
export const GET_TUTORADOS  = 'GET_TUTORADOS'
export const PUT_TUTOR = 'PUT_TUTOR'
export const SET_PAGINATION = 'SET_PAGINATION' 
export const PUT_TUTORADOS = 'PUT_TUTORADOS' 
